gwvolman/tasks.py
This is a complementary PR to whole-tale/girder_wholetale#131. If a Tale object contains `narrativeId` we download the content of that folder into the root of the mount point.
=> Download the Tale's narrative into the mountpoint

gwvolman/tasks.py
See https://github.com/whole-tale/girder_wholetale/pull/213
=> Update involatileData format in create_tale

gwvolman/tasks.py
Update `tale_import` task to take into account changes made in whole-tale/girder_wholetale#205.
Instead of looking for a folder in `/user/{}/Data`, ~we query `GET /dataset?myData=true` to get the most recently registered dataset. Note: `update` field is updated even if the dataset was previously registered.~, we query `GET /folder?name=<registered data name>` to get the folder id of the newly registered data. In case query returns empty array, we fallback to `GET /item?name=<registered data name>`.
1. Deploy locally, make sure you're using latest `deploy-dev@dev` (https://github.com/whole-tale/deploy-dev/commit/fcebd0340886ddec315467eaf063b892e592431c)
1. Follow: https://girder.local.wholetale.org/api/v1/integration/dataverse?fileId=3323458&siteUrl=https://dataverse.harvard.edu
1. Choose …
=> Update tale_import wrt whole-tale/girder_wholetale#205. Fixes #49

gwvolman/utils.py
Support size notation with units (b, kb, mb, gb)
1. Deploy locally
2. Launch a Tale
3. Verify that Tale container is limited to 2GB of RAM (`docker stats`)
=> Set mem_limit resource using int value. Fixes #52

gwvolman/utils.py
Information about girder, registry, dashboard external urls is derived using Docker Service API. As such, it only works on the master node. This PR defaults to env settings everywhere else.
This is an alternative fix to https://github.com/whole-tale/girder_wholetale/issues/289
=> Default to ENV settings when Docker Service API is not available

gwvolman/lib/dataone/publish.py
DataONE exceptions seem to be crashing the worker (see issue #67). This PR catches the DataONE exceptions and throws ValueError like the rest of the code base. 
I've tested this with an incorrect JWT and the JWT that was posted in the attached issue and haven't had gwvolman crash.
To Test:
1. Open the girder web api
2. Scroll to the publish/dataone endpoint
3. Fill in the Tale ID and `https://dev.nceas.ucsb.edu/knb/d1/mn` as the member node
4. Give a mangled JWT and attempt to publish
5. Give an expired JWT (see issue) and attempt to publish
In each case, you should get a ValueErrror, and gwvolman should still be running
=> Catch exceptions on generateIdentifier

gwvolman/lib/dataone/metadata.py
This PR adds functionality that maps the Tale authors to EML creators. I also set the EML dataset contact to the Tale creator. An example can be found [here](https://dev.nceas.ucsb.edu/view/urn:uuid:ca4d0b74-6282-4852-8d49-0072345adbc6). Linked to issue #60 
Testing:
2. Create a Tale with multiple authors
3. Publish
4. Visit the data package
5. Scroll to the bottom and make sure that the Tale authors are in the `Data Set Creators` section
6. Make sure that the Tale creator is in the `Data Set Contacts` section
7. Make sure the authors show up on the data landing page (see image below)
=> Add Tale Authors to EML

gwvolman/tasks.py
See https://github.com/whole-tale/girder_wholetale/pull/305 for details and test steps
=> Unified notification support

gwvolman/tasks.py
See https://github.com/whole-tale/girder_wholetale/pull/307 for details.
=> Allow build if workspace hasn't changed

gwvolman/tasks.py
Tale importing mishandled HTTP(s) resources
Currently, we register resources in two different ways:
1. DOIs (coming from Globus, Dataverse, DataONE, etc) create a root folder in the Catalog, that's named exactly the same as dataset.
2. HTTP(S) files are registered into Catalog using a nested structure based on their url (see whole-tale/girder_wholetale#266)
Knowing that, let's try to find the newly registered data by path.
1. Deploy locally, add ["https://dev2.dataverse.org"] to extra_hosts in plugin settings (https://girder.local.wholetale.org/#plugins/wholetale/config)
2. Follow https://dashboard.local.wholetale.org/compose?uri=https%3A%2F%2Fdev2.dataverse.org%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.5072%2FFK2%2FNYNHAM&name=Dataverse+IRC+Metrics&asTale=True and verify that Tale is …
=> Allow to create ad-hoc Tales with http(s) data. Fixes #81

gwvolman/tasks.py
See https://github.com/whole-tale/girder_wholetale/pull/347 for details
=> Empty Tale is now created before import starts

.circleci/config.yml, .coveragerc, Pipfile, Pipfile.lock, gwvolman/tests/test_containers.py
Enable basic tests with CircleCI.
=> [WIP] Add tests

gwvolman/tasks.py, gwvolman/utils.py
This PR decouples *repo2docker_wholetale* version from *gwvolman* version. It comes handy in two cases:
1. when *r2d_wt* needs updates outside of normal WT release cycle,
1. when we're importing a Tale and want to use a specific version of r2d.
Note: the fallback preserves the current behavior of using r2d_wt image specified by `REPO2DOCKER_VERSION` constant which is still tied to tags (or == "latest" for `master`)
1. Checkout this branch locally
1. Before deploying modify `setup_girder.py` in deploy-dev to create an additional RStudio Image (can be done later too if you prefer doing it manually)
* handy shortcut: `curl -s http://use.yt/upload/d89070f6 | patch -p1`
1. Go to dashboard.
1. Create new Tales:
1. with Image `RStudio`
1. with Image `RStudio (R 4.0.2)`
1. Run both and confirm …
=> Allow to specify r2d version via config on Image or Tale

gwvolman/constants.py, gwvolman/utils.py
Allow to set the location of license folder via env var (`WT_LICENSE_PATH`).
=> Allow to configure host license path. Fixes #125

gwvolman/utils.py
**Problem**:
We currently must modify each environment (see https://github.com/whole-tale/repo2docker_wholetale/pull/17) to customize CSP handling for iframes. This is not possible for the MATLAB Web Desktop integration, as CSP settings are not exposed.
**Approach**:
Use Traefik's `traefik.frontend.headers.contentSecurityPolicy` to set a suitable default CSP for iframes across environments.  Introduce a new `csp` configuration on images that can override the default, which is required by the new MATLAB IDE.
**Requires**:
* https://github.com/whole-tale/repo2docker_wholetale/pull/17
* https://github.com/whole-tale/deploy-dev/pull/39 (for matlab case)
**To Test**:
* Create and run Jupyter, RStudio, and MATLAB Desktop (Web Desktop) environments
* Confirm that IDEs are displayed in iFrame
=> Use Traefik to rewrite CSP for iframes

gwvolman/tasks.py
See https://github.com/whole-tale/girder_wholetale/pull/442
=> Remove obsolete folderId and narrative handling

gwvolman/constants.py, gwvolman/tasks.py
for those brave souls that click "View logs" in dashboard...
=> Add some basic log output to launch jobs

gwvolman/tasks.py, gwvolman/tests/test_recorded_run.py, gwvolman/utils.py
See https://github.com/whole-tale/wt_versioning/pull/35.
=> Add entrypoint parameter to recorded_run task

gwvolman/build_utils.py, gwvolman/tasks.py, gwvolman/tests/test_build_image.py, gwvolman/tests/test_recorded_run.py, gwvolman/utils.py
=> Use cached images for reproducible runs

gwvolman/tasks.py, gwvolman/tests/test_recorded_run.py
See https://github.com/whole-tale/wt_versioning/pull/38
=> Update run status based on job status

gwvolman/tests/test_build_image.py
I like my test reports green during releases...
=> Do not hardcode r2d tag in tests

Pipfile, Pipfile.lock, gwvolman/build_utils.py, gwvolman/tests/test_build_image.py, requirements.txt
Complementary PR to https://github.com/whole-tale/repo2docker_wholetale/pull/44/files
=> Handle --engine for newer r2d_wt

gwvolman/build_utils.py, gwvolman/tests/test_build_image.py
We don't always want to login to registry. This PR introduces `auth` kwarg to make that happen.
=> fix: make login to registry optional

gwvolman/tasks.py
Better to know that live an oblivious life...
=> enh: always log exception thrown by _rrun

gwvolman/tasks.py
companion to https://github.com/whole-tale/girder_wholetale/pull/564
=> Return a publiction info as a result of a publish task

gwvolman/tasks.py
In case RRun container survived gwvolman crash we need to remove it during cleanup.
=> Stop container in RecordedRunCleaner
