- gwvolman/utils.py
To support the swarm stack network prefix, added TRAEFIK_NETWORK environment variable with default value.
> Added TRAEFIK_NETWORK environment variable

- gwvolman/tasks.py
* Add `girder_job` decorator to automatically create jobs on girder side and get access to girder token. The latter is not utilized yet.
* Update `payload` for easy task chaining
> Convert gwvolman tasks into proper girder jobs

- gwvolman/utils.py
I still don't know how #12 happened, since right now we have a small, closed set of Images that do provide `rendered_command`... Anyway, that was a bug and should be fixed with this PR
> Provide sane defaults for rendered_{command,url_path}. Fixes #12

- gwvolman/dataone_metadata.py
- gwvolman/publish.py
- gwvolman/tasks.py
- requirements.txt
The changes here are for taking the tale and user as IDs and loading the objects internally. 
Lines 529&530 handle the loading of the objects.
There was also a bug fix for tales with empty descriptions.
> Handle Tale and User Ids Instead of Dicts

- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/utils.py
This PR switches default readonly filesystem from `RESTGirderFS` to `WTDmsGirderFS`. For the time being we initialize a session using Tale's `folderId`, which contains snapshot of involatile data.
> Use wt_dms file system for providing 'data' directory

- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/utils.py
This PR introduces new task that provided `imageId` and `url`:
1. Registers data identified by `url`
2. Creates Tale object using data from 1. and `imageId`
3. Optionally (`spawn=True`) instantiates the Tale.
> Add a task for streamlined Tale/Instance creation

- gwvolman/tasks.py
- gwvolman/utils.py
With this PR we infer dashboard's url directly from docker and construct appropriate CSP_HOSTS env variable, that's subsequently passed to Docker container running Tale instance. It solves multiple annoying issues:
* Manually editing Image objects on each new deployment
* Importing published Tales / Images that would have CSP_HOSTS hardcoded to a place where they were initially created.
Proposed test:
1. Using https://github.com/whole-tale/deploy-dev (branch *dev*), modify `setup_girder.py` so that images are created with wrong CSP_HOSTS setting or even without it.
1. Deploy with `gwvolman` pointing to *master* branch.
1. Run example Tale in the dashboard, to confirm iframes are **not** working
1. Switch `gwvolman` to this branch (*csp_inject*) and restart `celery_worker` via:
``` …
```
> Ensure that a proper CSP_HOSTS is passed to a container

- gwvolman/tasks.py
Fixes #41 - when a Tale is rebuilt, we need a way for the user to signal to the underlying instance that it should be restarted with the newest image.
Relates to https://github.com/whole-tale/girder_wholetale/pull/212
Add a general `update_container` task that can be easily expanded to cover additional related functionality, as needed.
There is currently not a super clean way to test this, as it currently requires running this code alongside the code from another PR to `girder_wholetale`.
So here goes:
1. Run [`deploy-dev`](https://github.com/whole-tale/deploy-dev/tree/dev) stack using the provided README instructions (make sure to use `dev` branch for now)
2. `cd src/gwvolman`, `git fetch --all`, and checkout this branch
* NOTE: You may need to restart the worker with `make …
> Added a new task for updating a running container's image

- gwvolman/utils.py
Host in `""` no longer works for RStudio 1.2.x
> Tweak CSP_HOSTS setting to match the behaviour of new RStudio

- Dockerfile
Per davfs2 man:
```
use_locks
Whether to lock files on the server when they are opened for writing. 0 = no, 1 = yes.
gui_optimize
When a file is opened, mount.davfs will have to check the server whether there is a newer version. 
Graphical User Interfaces tend to open just any file, slowing down things dramatically for large 
directories. With this option mount.davfs will try to get this information from all files in a directory with 
one PROPFIND request. 0 = no, 1 = yes.
Default: 0
```
makes UX more smooth at the cost of (possible?) data corruption. We should send a clear message to the users that multiple concurrent, intensive and distributed i/o workloads on webdav mounts are a bad idea...
As a bonus, we are hiding `lost+found` by prefixing it with a `.`.
> Disable use of locks for davfs. Fixes #51

- gwvolman/tasks.py
- gwvolman/utils.py
Fixes #40.  See https://github.com/whole-tale/girder_wholetale/pull/211 for test case.  
This PR requires:
* https://github.com/whole-tale/girder_wholetale/pull/211 
* https://github.com/craig-willis/repo2docker/pull/1 for WT customizations to `repo2docker`
This PR does the following:
* Refactors `build_image to `build_tale_image` to run `repo2docker` on the Tale workspace
* Downloads Tale workspace folder via `girder_client.downloadFolderRecursive` to temp directory
* Builds the image using `repo2docker`
* Removes temp directory
* Pushes image to registry
* Returns image digest for use in instance creation
There are a few open issues:
* How to handle `repo2docker` version pinning
* How to handle commit-hash.  For now, append the time, but we'll have tag proliferation. Need a way to …
> Build Tale image using repo2docker

- gwvolman/tasks.py
Trailing slash in  dataSet is not necessary and is confusing the dashboard.
> Do not add a trailing slash to dataSet entries

- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
This fixes the issue described in issue #57 and should suffice for issue #48.
`mimetypes.guess_type` returns a tuple which was getting sent to `get_dataone_mimetype`, causing it to return `application/octet-stream`.
> Check DataONE Mimetypes

- gwvolman/tasks.py
`import_tale` was using outdated schema, which broke this functionality. Instead of trying to set `authors` based on person who's creating a Tale, we're setting it to an empty list to avoid problems during potential publishing.
1. Deploy locally
2. Add ["http://dev2.dataverse.org"] to list of Extra Dataverse Installations (https://girder.local.wholetale.org/#plugins/wholetale/config)
3. Try creating tale by following: https://dashboard.local.wholetale.org/compose?uri=http%3A%2F%2Fdev2.dataverse.org%2Fapi%2Faccess%2Fdatafile%2F29
> Use new schema for authors field in "Analyze in WT" (whole-tale/girder_wholetale#273)

- gwvolman/tasks.py
With this PR, `update_container` task emits progress updates when it starts and when it ends. Additionally, job is not completed until one of the following conditions is met:
1. New container is up and running.
2. Task is cancelled.
3. Updating service timeouts (after 3 minutes).
4. Updating service fails. 
The latter 2 cases result in ERROR job status.
1. Run a Tale, update environment by modifying. Hit "restart tale"
2. Using Girder's UI (My Jobs) confirm that job is running until the service is restarted
Note: Girder should also display notification toast in the lower right corner
> Provide updates during instance restart

- gwvolman/lib/dataone/constants.py
- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
- gwvolman/tasks.py
This PR removes the environmental variable for the CN and uses the DataONE Python library to keep track of them.
I added a variable to the publishing task to help us figure out which CN to use.
To test:
I accidentally published to production with this code, so try to avoid that.
2. Check [add_prod_publishing_flag](https://github.com/whole-tale/girder_wholetale/pull/301) out
3. Check [dataone_login_refacor](https://github.com/whole-tale/dashboard/pull/474) out
4. Try to publish to dataone dev
5. You should get a valid package
Attached to issue #72
> Switch from using the environmental variable CN. Fixes #71

- gwvolman/lib/dataone/publish.py
Linked to issue #73 
This PR switches to assigning DataONE internal identifiers for files, but leaves a DOI for the EML document. An example dataset can be found [here](https://dev.nceas.ucsb.edu/view/urn:uuid:6bcd52d0-ae8e-4cfe-89f0-b013205760a8). Note how the DOI is at the end of the title, and is listed under `identifier` in the "General" section.
I removed the TODO comment because the d1 python library is using the API under the hood.
To Test:
2. Publish a Tale to DataONE development
3. Make sure that the package URL is _not_ a doi
4. Note that a doi is listed as the package identifier and is in the title
> Generate UUIDs for everthing except the EML document

- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/utils.py
The new https://github.com/whole-tale/repo2docker_wholetale repository implements WT images (Jupyter, Jupyter + Spark, Rocker, OpenRefine) via custom build packs using the model discussed in https://github.com/jupyter/repo2docker/issues/487#issuecomment-479794426.
This PR changes the gwvolman build_tale task to use the new approach.  In short, an `environment.json` is injected into the workspace at image build time. This file contains information needed to select the correct build pack.   This PR also moves the repo2docker image version to a constant for use in the girder_wholetale plugin (https://github.com/whole-tale/girder_wholetale/pull/308).
To test (via deploy-dev):
* Checkout this gwvolman branch
* `docker logs -f celery_worker`
* Compose new tale using RStudio (rocker geospatial) …
> Integrate with new repo2docker_wholetale extension

- gwvolman/tasks.py
- gwvolman/utils.py
Have you ever run a Tale and something went awfully wrong? Have you ever spent egregious amount of time trying to figure out where the heck it was running to see what happened? Fret no more! With this fabulous PR soon you'll be able to do it in a flash! Behold amazing docker magic:
```
docker service ps $(docker service ls -f label=wholetale.instanceId=5cfeac6f72ef511908fcc612 -q)
```
1. Run a Tale.
1. `docker inspect` Tale container and confirm that `wholetale.instanceId` and `wholetale.taleId` are set.
> Label services with Instance/Tale Id

- gwvolman/utils.py
This removes spurious line breaks from job logs from image builds.
1. Deploy locally and register Ligo tale.
2. Run Ligo tale.
3. Click on "View logs" in the notification panel during image build and confirm that log is nice and tidy.
> Strip EOL from docker logs

- gwvolman/lib/dataone/constants.py
- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
This PR fixes issue #83. This should be *fully* testable when we add support for file hierarchies on the DataONE side.
An example data package can be found [here](https://dev.nceas.ucsb.edu/view/urn:uuid:b45592e9-2c3e-4757-be23-af37f440c8f0)
The changes made here aren't that drastic. I use the bagit exported instead of native, which of course includes some additional files we don't want to put in the package (bagit.txt and friends)-you can see where I skip these in the code.
The two additional files follow the same paradigm as the environment and manifest, which amounts to
1. Creating new records in `constants.py`
2. Grabbing their file size and computing their md5
3. Sending the file size to the EML generation code
4. Adding the entries to the EML, using the info from steps 1 and 3
1. …
> Upload a subset of the exported bag to DataONE

- gwvolman/constants.py
- gwvolman/tasks.py
This is a complementary PR to https://github.com/whole-tale/girder_wholetale/pull/350
1. Tale Image is only built if Tale's status is READY
2. During Tale import, Tale status is set to ERROR whenever the process raises an error.
> Don't build Image until Tale status is READY

- gwvolman/tasks.py
After data is registered, TaleStatus is now updated to READY. 
Note: ~I haven't tested it~, https://search-demo.dataone.org/view/10.24431_rw1k333_201997221052 gives me SyntaxError, but other datasets work fine.
> Update Tale status after import is done. Fixes #87

- gwvolman/tasks.py
This PR adds the base_url to the call to register the dataset.
Fixes https://github.com/whole-tale/girder_wholetale/issues/366
To Test
1. Deploy Locally
2. Try creating a Tale from the two URLs. One specifies the base_url, while the other one doesn't
`https://dashboard.local.wholetale.org/browse?uri=urn%3Auuid%3Adcf99f66-4a33-49c5-bd17-8f4332a15ebe&name=A+global+database+of+chlorophyll+and+water+chemistry+in+freshwater+lakes&api=https%3A%2F%2Fdev.nceas.ucsb.edu%2Fknb%2Fd1%2Fmn%2Fv2&environment=OpenRefine` 
and
`https://dashboard.local.wholetale.org/browse?uri=doi:10.18739/A2CN6Z03F&name=Dissolved nutrient concentrations, High Arctic Ocean, August-September 2018&environment=OpenRefine`
3. Make sure you see the data in the Tale
> Pass the base_url to dataset/register

- gwvolman/lib/dataone/publish.py
We are currently storing the resource map ID in the Tale's `pid` field. I think it makes more sense to save the doi here, which is what we do with Zenodo. We assign the doi to the EML document, which is why I use the `eml_pid` in the code change.
To Test
2. Publish a Tale to Dev DataONE
3. Use the girder endpoint to look at the Tale's publishInfo
4. Make sure that you see a doi in the `pid` field.
5. Make sure that you see the member node in the `repository` field
6. Make sure that the ID in the `repository_id` field matches the resource map ID on the dataset landing page
> Store the DOI as the Tale 'pid'

- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
- gwvolman/tests/test_publish.py
Fixes #94 
1. We now store the coordinating node without the `v2/` at the end.
2. The coordinating node client takes care of retrieving the supported formats
2. Publish a Tale to DataONE
3. Download the resource map at https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/<PACKAGE_PID>
4. Ensure that the RDF subject URIS have a single `v2`.
For example, the package [here](https://dev.nceas.ucsb.edu/view/doi:10.5072/FK2JS9RT3D) with resource map [here](https://dev.nceas.ucsb.edu/knb/d1/mn/v2/object/urn:uuid:2b084f1a-e498-46aa-8eb6-36b71a161b41) has valid subject URIS
`<rdf:Description rdf:about="https://cn-stage-2.test.dataone.org/cn/v2/resolve/urn:uuid:5adba71f-d2bb-417e-a63b-a982be1b127b">`
`  <rdf:Description rdf:about="https://cn-stage-2.test.dataone.org/cn/v2/resolve/ …
> Check if the DataONE endpoint already has a v2

- gwvolman/constants.py
- gwvolman/lib/publish_provider.py
- gwvolman/lib/zenodo.py
- gwvolman/tests/test_publish.py
Create a new version of a Zenodo deposition for a subsequent Tale publications.
1. Create and publish a Tale to `sandbox.zenodo.org`
2. Change something (files or metadata) and publish again
3. Confirm that new version of existing deposition was created.
> [zenodo] use new version for subsequent Tale publications

- gwvolman/lib/zenodo.py
- gwvolman/tests/test_publish.py
This PR adds Tale's related identifiers to Zenodo's deposition in order to show them in their UI.
Also fixes format of the doi in `publishInfo`, which is needed for https://github.com/whole-tale/girder_wholetale/pull/396
1. Create a Tale via AinWT from Dataverse or DataONE. Use `asTale=True` to get `IsDerivedFrom`, cause `cites` was already there.
2. Publish to Zenodo. Check if related identifier is there
> Zenodo related ids

- gwvolman/lib/zenodo.py
Instead of trying to guess the resource server during import, we can actually set it as query parameter in the link we craft during publication... Makes the resulting url work outside Zenodo.
1. Publish a Tale
2. Copy a link from "Run this Tale on Whole Tale by clicking *here*." into separate browser window or embed it in hackmd.io markdown page and see if it works
> Add 'resource_server' to import link

- gwvolman/lib/dataone/constants.py
- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
- gwvolman/tests/test_publish.py
This PR is a compliment to https://github.com/whole-tale/girder_wholetale/pull/401
The code changes are pretty standard. With the changes in the linked issue above, a published package will miss the README file. Since it's no longer in the manifest, we treat it like the fetch, run-local, environment, and manifest.json file.
For testing, refer to the linked issue.
> Publish the README as an extra file

- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
We can include citation information in the DataONE ORE about datasets that the Tale has cited. This is a small code change that looks through the manifest for datacite citations, and then adds them to the ORE.
This will be ready to test when a small fix to the manifest is made. I'll remove this warning and assign reviewers when it's done.
To Test:
1. Deploy this branch
1. Use a Tale that has a citation link (you can update the Tale to have the snippet at the bottom)
1. Publish to DataONE Dev
1. Download the resource map
1. Search inside the resource map for `references` and make sure that you see the identifier from "relatedIdentifiers" referenced
To Download the resource map:
1. Visit the dataset landing page
1. ctrl+f 'Files in this dataset Package'
1. Copy the ID to the right of the …
> Add dcterms:references relationship to DataONE resource maps

- gwvolman/lib/zenodo.py
- gwvolman/tests/test_publish.py
`record_html` always resolves and DOI is stored in `doi` either way.
> [zenodo] use record link for uri. Fixes whole-tale/girder_wholetale#406

- Dockerfile
This PR changes the value of `delay_upload` in `davfs2.conf` from the default 10 seconds to 0 seconds.
**Problem**:
When two users are editing the workspace for a shared tale, workspace changes from one user are not propagated to the other for 10 seconds. Also, in the past when rebuilding a tale the user had to wait 10 seconds for changes to be recognized by the system. This is because the davsfs2.conf `delay_upload` setting defaults to 10 seconds.
From the docs:
> delay_upload: When a file that has been changed is closed, mount.davfs will wait that many seconds before it will upload it to the server. This will avoid uploading of temporary files that will be removed immediately after closing. If you need the files to appear on the server immediately after closing, set this option to 0. …
> Set delay_upload to 1

- Pipfile
- Pipfile.lock
- gwvolman/tasks.py
- requirements.txt
Fixes #121 
**Approach**:
Use the new folder["updated"] field introduced by https://github.com/whole-tale/virtual_resources/pull/10 in place of tale[workspaceModified] to detect workspace changes during build.
**Prerequisites**:
* https://github.com/whole-tale/girder_wholetale/pull/433
* https://github.com/whole-tale/virtual_resources/pull/10
* `docker pull gwvolman/latest` (see https://github.com/whole-tale/gwvolman/pull/122)
**Test steps**:
* Create a JupyterLab tale
* Run the tale
* Create `apt.txt` with contents `vim`
* Rebuild the tale
* The image should rebuild
> Use new updated time to detect workspace modifications

- gwvolman/utils.py
This PR 
* Adds `licenses` directory mounted into running containers
* Adds `--build-arg` to pass Matlab installation key during build
See https://github.com/whole-tale/deploy-dev/pull/39 for full test case.
> Matlab support

- gwvolman/tasks.py
- gwvolman/utils.py
This PR:
* Revises how licenses are mounted based on buildpack
See whole-tale/deploy-dev#40 for full test case.
> Stata support

- gwvolman/lib/publish_provider.py
- gwvolman/tests/test_publish.py
This came up during discussion related to https://github.com/whole-tale/girder_wholetale/pull/440. In a gist: when we export Tales out of the system, we need to make sure that ephemeral references (like DV subfolders) are expanded into actual physical objects.
> Published dataSet must be expanded

- gwvolman/utils.py
This PR removes a misplaced `=` that causes the following warning in the dev console:
```
The source list for Content Security Policy directive 'frame-ancestors' 
contains an invalid source: '='self''. It will be ignored
```
> Fix CSP warning

- gwvolman/lib/dataone/metadata.py
- gwvolman/lib/dataone/publish.py
Fixes issue #107. This is a rewrite of a much uglier PR (#111 ). This PR does _not_ include the refactored unit tests, but _does_ give a little more clarity into the Tale updating changes.
The first two commits just pull things into a few classes to make things easier down the road. The next few fix up a few pep issues. The last commit fixed this issue where one except statement was swallowing an exception from a nested try/catch. I flattened the try/catch blocks and things seem to be working fine.
#115 should be merged after this PR is merged.
A Tale is 'updated' when it's published a second time. If a Tale is published to DataONE, and then a copy is made and 
subsequently published the `datacite:IsDerivedFrom` relation pointing to the first Tale's doi is added to the resource map of the …
> Update dataone tales

- gwvolman/utils.py
See https://github.com/whole-tale/deploy-dev/pull/44 for test and https://github.com/whole-tale/whole-tale/issues/94 for problem description.
This PR changes annotations to Traefik v2 format.
> Migrate to traefik v2 and add support for forward auth

- requirements.txt
"Fixes" issue seen on stage deployment:
```
[2021-03-21 19:09:01,870: INFO/ForkPoolWorker-4] Successfully built image registry.stage.wholetale.org/605792f48b171335abe6d3d2/1616352419@sha256:25ce82fdb6a492f91c6f08e682b30b5ad9df0015ffcd3d9d79bd1f5ed45d123d
[2021-03-21 19:09:02,036: WARNING/ForkPoolWorker-4] /usr/local/lib/python3.8/dist-packages/celery/app/trace.py:622: RuntimeWarning: Exception raised outside body: AttributeError("'dict' object has no attribute 'apply_async'"):
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/kombu/utils/objects.py", line 42, in __get__
return obj.__dict__[self.__name__]
KeyError: '_apply_async'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File …
```
> Pin jsonpickle. See whole-tale/girder_wholetale#447

- gwvolman/tasks.py
Have you ever been annoyed by the fact that changing the base Image and hitting "Rebuild Tale" results in noop and a lousy message "Workspace not modified. Skipping build"? If so, this PR is for you!
1. Needs https://github.com/whole-tale/girder_wholetale/pull/472
2. Create a Tale with RStudio. Launch it.
3. After instance is up, go to Metadata page and change image.
4. Using Tale Action menu click "Rebuild Tale"
5. Confirm that image is being built even if you didn't touch the workspace.
> Always rebuild image if tale's imageId has changed

- gwvolman/tasks.py
- gwvolman/utils.py
This PR fixes https://github.com/whole-tale/gwvolman/issues/144 and adds additional handling for container launch failures by
* Increasing launch timeout from 30s to 5m for very large images (looking at you, MATLAB)
* Raising an exception when the container enters a `failed` or `rejected` state
* Raising an exception when the container start exceeds the timeout
* Adding a restart policy with condition=none to prevent restart on failure
> Add launch timeout and failure handling

- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/tests/test_volumes.py
- gwvolman/utils.py
**This PR**
* Implements the `recorded_run` task which:
* Builds the image for the specified version/run
* Mounts workspace and data for the specified version/run
* Executes `reprozip --trace ... ./run.sh` using the user's image, which generates output in the run workspace `.wholetale` directory
* Executes CPR reports which generate output into `.wholetale/.cpr` directory
* Also
* Moves volume creation/mounting code into helper functions that can be used by new recorded_run task
* Modifies _build_image helper to enable use by recorded_run task
* Adds tests
**To Test**
* Depends on
* https://github.com/whole-tale/wt_versioning/pull/29
* https://github.com/whole-tale/repo2docker_wholetale/pull/21
* https://github.com/whole-tale/wt-cpr
* Create a tale with an executable `run.sh` in the …
> Recorded run task

- gwvolman/utils.py
The day has come to fix that "FIXME"...
1. Deploy and spawn instance. Check if volumes are mounted
2. (optionally) the really hard way would be to change `Docker Root Dir` and do 1. again, but IMHO that's a waste of time... (I tested this on .radiant)
> Avoid hardcoding mountpoint

- gwvolman/constants.py
- gwvolman/tests/test_build_image.py
- gwvolman/utils.py
See https://github.com/whole-tale/repo2docker_wholetale/pull/26 for test case.
To support installing custom STATA packages at build time (e.g., `install.do`) we need to provide the license file at build time.  I considered two options: 
1. using `RUN --mount` and copy the license from an image or 
2. pass the license as a build-arg. 
I went with option 2 here since we're already passing the MATLAB installation key as a build arg.  Because the license contains shell-interpretable characters (`$!`), I encode before passing and decode in the StataBuildPack.
> Pass encoded STATA license as r2d build arg

- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/tests/test_volumes.py
Adds the runs volume to the instance container.
To test:
* Requires https://github.com/whole-tale/girderfs/pull/29
* Start a tale instance
* Create a recorded run
* `ls ../runs` and confirm the run is there and accessible
> Add runs volume

- Pipfile
- Pipfile.lock
- gwvolman/build_utils.py
- gwvolman/constants.py
- gwvolman/lib/dataone/publish.py
- gwvolman/tasks.py
- gwvolman/tests/test_build_image.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/utils.py
Tag Tale images using the checksum of r2d files and r2d short_id. Then during `build_image` phase check if given image exists in the local registry. This allows for more efficient caching even for completely new tales.
1. Create a Tale. Run it. Shut it down.
1. Upload a file "hello.txt" (or anything not r2d related) to the workspace. Run the tale.
1. It should skip the build phase.
1. Upload `apt.txt` with any sane content.
1. Run the tale. It should build a new image.
1. Stop and delete the Tale.
1. Create a new Tale, upload the same `apt.txt`, run the tale.
1. It should skip the build phase.
> enh: cache images based on r2d files checksum

- gwvolman/tasks.py
- gwvolman/tests/test_volumes.py
- gwvolman/utils.py
Re-do of #153 . This time I'm doing "the right thing"^{TM} and grab the required information from `create_volume` task's result.
> Avoid hardcoding mountpoint (done right)

- gwvolman/lib/dataone/publish.py
Missed this when implementing https://github.com/whole-tale/girder_wholetale/pull/525. 
This PR adds the bagit *manifest-sha1.txt files to the ignore list for publishing to DataONE
> Add manifest sha1 files to ignore list

- gwvolman/lib/dataone/publish.py
When publishing to D1, the serialized ResourceMap is RDF but needs to be EML. This PR uses the `ResourceMap.serialize_to_transport()` method instead of the `rdflib.graph.ConjunctiveGraph.serialize()`.
See also  the docs for `d1_common.resource_map.ResourceMap` https://dataone-python.readthedocs.io/en/latest/d1_common/api/d1_common.html
**To Test**:
* Requires https://github.com/whole-tale/girder_wholetale/pull/528
* Create and publish a Tale as described in https://github.com/whole-tale/girder_wholetale/pull/528
> Use serialize_to_transport to generate valid EML

- gwvolman/lib/dataone/publish.py
- gwvolman/lib/zenodo.py
- gwvolman/tasks.py
This PR partially addresses https://github.com/whole-tale/whole-tale/issues/117. It's not meant as a comprehensive solution and as-is it's very easy to circumvent (switch between versions, re-import, basically anything that change `versionId`). However, it excels at preventing the most common "mis-use" of publish in WT: user double clicking 'publish' in the publication modal or repeated attempt of publishing the same Tale without any modifications...
1. Create a Tale.
2. Publish it to DataONE or Zenodo. Operation should work
3. Repeat 2. (using the same provider). Operation should fail.
> Prevent 'double' publish of the same version of a Tale

- gwvolman/tests/test_recorded_run.py
- gwvolman/utils.py
Super minor, but the container name seems meaningless in this context.
> Drop container name from stats

- Pipfile
- Pipfile.lock
- gwvolman/tasks.py
- gwvolman/tests/test_volumes.py
- requirements.txt
Deployed on .test. Requirements for testing:
- latest `wholetale/girder:latest` for matching UID/GID in girder container.
- nfs mount of `/mnt/homes` on each slave node on multiple deployments OR `-e WT_VOLUMES_PATH="$PWD"/volumes` in `deploy-dev:run_worker.sh`
1. Run a Tale and do some stuff in workspace, ensure that anything that happens is reflected in fs state
2. Same as 1. but for home.
> Switch to bind mounts for home/workspace

- gwvolman/utils.py
**Problem**:
`containers.create()` does not pull the image. It is possible to start a recorded run on a node where the image does not already exist or before it is built.
**Test**:
* TBD
> Pull image before recorded run

- Pipfile.lock
- gwvolman/build_utils.py
- gwvolman/tests/test_build_image.py
Noop rewriting logic in `ImageBuilder.engine()` to remove `packaging.version.LegacyVersion` that was dropped in most recent `packaging`.
> Drop usage of deprecated packaging.version.LegacyVersion

- gwvolman/build_utils.py
- gwvolman/constants.py
- gwvolman/tasks.py
- gwvolman/tests/test_build_image.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/utils.py
This adds checks for `task.canceled` in long running tasks: `image_build` and `recorded_run`. In the latter case also tries to clean-up leftovers nicely.
1. Create a Tale, build image (preferably with a custom Dockerfile so you don't hit cache).
2. In girder UI navigate to job view (click on job name in notification). Click 'cancel'. Job should turn to "Cancelling" than "Canceled" after a while.
3. Create a Tale, upload `entrypoint.sh` with steps that take some time (e.g. `echo "1" && sleep 10; echo "2" && sleep 10;...`). Run recorded run. Repeat 2. In dashboard UI run should also be in "Canceled" state in the end.
> Make image build and rrun cancelable

- gwvolman/build_utils.py
- gwvolman/tasks.py
Fixes https://github.com/whole-tale/whole-tale/issues/126
**Test case:**
* Assumes image has never been built
* Create tale from https://github.com/whole-tale/rrun-test
* Start recorded run without first building image via Run Tale or Build Image
* Confirm that image is built, pushed, and run succeeds.
> Use build_context when building image for recorded run

- gwvolman/build_utils.py
LICENSE_PATH is absolute  and `os.path.join(HOSTDIR, LICENSE_PATH)` results in just `LICENSE_PATH`
> Fix stata license path location within gwvolman container

- gwvolman/tasks.py
- gwvolman/tests/test_cleanup_tasks.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/utils.py
This adds two tasks:
1. A simple task that return `True` if container named `name` is in a state `running`. Return `False` in every other case.
2. A task that initializes `RecodedRunCleaner` based on data stored in RRun folder (which now happens in recoded run task here: https://github.com/whole-tale/gwvolman/pull/195/files#diff-88a81f7b7546ed0912d4ef71c6547bb35dbb0c312d93c8007e09118dde24ea56R738-R748) and performs cleanup. Additionally it updates the original job with an error status.
companion to https://github.com/whole-tale/wt_versioning/pull/52
Successful clean up should look like this:
```
[2023-03-10 20:45:17,950: INFO/MainProcess] Connected to redis://redis:6379//
[2023-03-10 20:45:17,952: INFO/MainProcess] mingle: searching for neighbors
[2023-03-10 20:45:18,963: …
```
> Add a task for cleaning orphaned rruns

- gwvolman/build_utils.py
- gwvolman/tasks.py
- gwvolman/tests/test_build_image.py
- gwvolman/tests/test_deployment.py
- gwvolman/utils.py
Currently we use `TMPDIR` for 2 things:
1. As a place to prepare build context for repo2docker
2. For caching WtDmsGirderFs files.
Due to 2. we need TMPDIR to be fairly big, which we can achieve by mounting a particular resource from host to `celery_worker`'s `/tmp`. However, we now have to make sure that whatever resource is mounted as `/tmp` also gets mounted the same way for r2d container, which is the goal of this PR.
1. Create a new subdirectory in `volumes` called `tmp`, and make sure it has proper acls (`chmod 1777 volumes/tmp`)
2. Modify `run_worker.sh` with:
```diff
--- a/run_worker.sh
+++ b/run_worker.sh
@@ -33,7 +33,7 @@ docker run \
-e WT_VOLUMES_PATH="$PWD"/volumes \
-e MATLAB_FILE_INSTALLATION_KEY=${matlab_file_installation_key} \
-v …
```
> if tempdir is mounted use the same path for r2d

- .circleci/config.yml
- gwvolman/__init__.py
- gwvolman/constants.py
- gwvolman/fs_container.py
- gwvolman/tasks.py
- gwvolman/tests/__init__.py
- gwvolman/tests/conftest.py
- gwvolman/tests/lib/test_publish_provider.py
- gwvolman/tests/lib/test_zenodo_publish.py
- gwvolman/tests/test_build_image.py
- gwvolman/tests/test_deployment.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/tests/test_volumes.py
- gwvolman/utils.py
- requirements-dev.txt
Summary of changes:
1. Most logic/code related to mounting fses was moved to https://github.com/whole-tale/girderfs/pull/38
2. Mounting/unmounting is done via running/stopping a dedicated sidecar container
3. An assumption that `celery_worker` is running in a regular container, were replaced by the notion of `celery_worker` running as a swarm service (see changes in `gwvolman/utils.py`)
4. WT deployments rely upon specific queues being defined. Up till now, that was handled by manually passing their names in `run_worker.sh` on each node. With this PR, everything happens automatically (see changes in `gwvolman/__init__.py`) 
Fixes https://github.com/whole-tale/gwvolman/issues/196
> Use GirderFS http server for mounts

- gwvolman/fs_container.py
- gwvolman/tests/test_recorded_run.py
- gwvolman/tests/test_volumes.py
Should fix intermittent failures we've seen on slower systems, e.g.
```
[2023-06-12 14:43:54,764: WARNING/ForkPoolWorker-1] Sending payload to WT Filesystem container...
[2023-06-12 14:43:54,788: ERROR/ForkPoolWorker-1] Task gwvolman.tasks.create_volume[fbf6448c-f851-497d-ac4a-3782e8e46ccb] raised unexpected: ConnectionError(MaxRetryError("HTTPConnectionPool(host='6481e4c123e04ab3d99445bd_cawillis_foomex', port=8888): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fec583f2dd0>: Failed to establish a new connection: [Errno 111] Connection refused'))"))
Traceback (most recent call last):
File "/home/wtuser/venv/lib/python3.10/site-packages/urllib3/connection.py", line 174, in _new_conn
conn = connection.create_connection(
File …
```
> Add a retry for connection error in fs_container

- gwvolman/tests/test_recorded_run.py
- gwvolman/utils.py
This is required when Tale uses it's own Dockerfile.
> Ensure that mounted workspace is rrun's working directory

- gwvolman/r2d/remote.py
- gwvolman/remote_builder/server.py
- gwvolman/tasks_kubernetes.py
- gwvolman/utils.py
- gwvolman/utils_k8s.py
- setup.py
* More robust handling of registry url
* [remote_builder] Ensure that r2d user belongs to docker group
* Add support for `subPath` in k8s volume mounts
* Specify cpu/memory limits for tales.
> fix: finalize support for K8S deployment @ JHU
